<?php
if($_SERVER['REQUEST_METHOD']=='POST'){
$result1='10';
$result2='16';
$result3='4';
$result4='6';
$result5='3';
$result6='10';
$result7='16';
$result8='11';
$result9='14';
$result10='2';
$counter=0;
$name=$_POST['username'];                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
$ans1=$_POST['ans1'];
$ans2=$_POST['ans2'];
$ans3=$_POST['ans3'];
$ans4=$_POST['ans4'];
$ans5=$_POST['ans5'];
$ans6=$_POST['ans6'];
$ans7=$_POST['ans7'];
$ans8=$_POST['ans8'];
$ans9=$_POST['ans9'];
$ans10=$_POST['ans10'];
if($ans1==$result1)
$counter+=10;
if($ans2==$result2)
$counter+=10;
if($ans3==$result3)
$counter+=10;
if($ans4==$result4)
$counter+=10;
if($ans5==$result5)
$counter+=10;
if($ans6==$result6)
$counter+=10;
if($ans7==$result7)
$counter+=10;
if($ans8==$result8)
$counter+=10;
if($ans9==$result9)
$counter+=10;
if($ans10==$result10)
$counter+=10;
echo "<h1>".$name." "."your grade is"." ".$counter."%"."</h1>";
}
else "you cannot enter directly";
?>